### ISSUE TITLE
Interference with pg-promise

### ISSUE THREAD

**Issue by ramalhoruben** [olalonde/pgtools#10]
I am a newbie regarding nodejs and promises, learning as I go... :) 

I have been having a problem  where this module interferes with pg-promise.  Pg-promise will connect to the public database instead of the specified database.. it seems to be reusing the connection created by this module. When I don't use pgtools functionality pg-promise will work as expected.

This might be due to the connection not being closed properly.

**Comment by olalonde** [comment]
That's weird, I don't think this module uses any sort of pool. Maybe `pg-promise` is monkey patching `pg` in some weird way or maybe you're setting the `PG_CONNECTION_STRING` env variable and it is overriding your configuration somewhere?

**Comment by bcoe** [comment]
@olalonde @ramalhoruben I believe `pg` has a connection pool it configures behind the scenes; my bet would be that there's a bad interaction between the configuration you're using to setup `pgtools`, and `pg-promise`.

I've been using `pgtools` mainly in npm scripts, like so:

``` json
{"scripts": {
    "test:db": "createdbjs useracl_test; DB_USER=${PGUSER:-$USER} DB_NAME=useracl_test npm run db:migrate",
 }}
```

**Comment by olalonde** [comment]
It's possible but AFAIK we're not using pg's built in pooling since we're using `pg.Client` directly instead of `pg.connect`: https://github.com/brianc/node-postgres/wiki/Client#constructors

> note: Client instances created via the constructor do not participate in pg's connection pooling. To take advantage of connection pooling (recommended) please use either pg-pool or a pooling utility such as pgbouncer.

**Comment by vitaly-t** [comment]
@olalonde 

> Maybe `pg-promise` is monkey patching pg in some weird way or maybe you're setting the `PG_CONNECTION_STRING` env variable and it is overriding your configuration somewhere?

It does neither (I am the author of `pg-promise`). And it uses `.connect` for connecting to the database.

@ramalhoruben just so, `pg-promise` has never been reported to conflict with anything. It uses `node-postgres` in the standard way exactly, through the connection pool.

**Comment by ramalhoruben** [comment]
Thanks you all for your feedback and time expended regarding this matter.

While creating a minimal example I came to realize that the problem was in my part of code.
I was using such a structure on my configuration file:

``` javascript
var conn = {
  host: 'localhost',
  port: 5432, 
  database: 'example',
  user: 'postgres',
  password: 'pass1234'
};
```

But since pgtools doesn't expect a 'database' attribute naively I did something like this:

``` javascript
function create_db(config){
    //Retrieve system configuration
    var conn = config.get('conn');
    var dbname = config.get("db_config").pg_dbname;
    delete conn['database']

    return pgtools.createdb(conn, dbname);
}
```

I was naive enough to think that javascript would make a deep copy of the object, instead I directly edited the configuration object thus leaving pg promise without database information.. I guess he was connecting to public because of this. @olalonde may I suggest an error or warning regarding this situation?

**Comment by olalonde** [comment]
Oh I see... Actually we shouldn't be mutating the config object passed as an option (https://github.com/olalonde/pgtools/blob/master/index.js#L20), this is definitely a bug, we should make a copy instead.

@bcoe maybe we should do something like `Object.assign(opts, { database: 'postgres' })`? or just manually copy the properties on another object since Object.assign is not supported in older Node.js? Want to do it?

**Comment by bcoe** [comment]
@olalonde sorry for the slow reply, digging myself out from a big OSS backlog.

Would it be alright if we use https://www.npmjs.com/package/object-assign, I'm currently using this library on a couple codebases that I haven't ported to Node 4 yet :p

**Comment by olalonde** [comment]
Yes, sure! Or if you want to go all in with babel + babel runtime, I've no objection. As long as we don't mutate w/e is passed as an argument because that's usually unexpected right.

**Comment by adriaandotcom** [comment]
I want to start with a clean slate. So closing this issue as it's from 2016. Please reopen any issue if it's still a problem at the moment.
