### ISSUE TITLE
create user?

### ISSUE THREAD

**Issue by stevenvachon** [olalonde/pgtools#16]
Is this possible?

**Comment by olalonde** [comment]
Not at the moment, but a pull request would be welcome.

**Comment by stevenvachon** [comment]
I ended up using [knex](https://npmjs.com/knex):
```js
promiseTry(() => psql = knex({ client:"pg", connection:{ host } }))
.then(() => psql.raw("create database ??", name))
.then(() => {
	// Passwords within "create user" are specifically disallowed bindings in https://npmjs.com/pg
	const query = psql.raw("create user ?? with encrypted password ?", [user, password]).toString();
	return psql.raw(query);
})
.catch(error => {
	console.error(error);
	process.exitCode = 1;
})
.then(() => psql.destroy());
```

**Comment by bcoe** [comment]
@stevenvachon would love to support this 👍 I think we'd be smart to eventually support this whole list, with a similar command line interface:

https://www.postgresql.org/docs/9.0/static/reference-client.html

**Comment by adriaandotcom** [comment]
I want to start with a clean slate. So closing this issue as it's from 2017. Please reopen any issue if it's still a problem at the moment.
