### ISSUE TITLE
Maintained alternative?

### ISSUE THREAD

**Issue by adriaandotcom** [olalonde/pgtools#23]
I love this package, but it's not maintained anymore.

Does anybody know an alternative?

Or are you open to give more maintainers access to pgtools, @olalonde?

**Comment by olalonde** [comment]
Sure, would you like to maintain it? If so, give me you npm username and I'll add you.

**Comment by adriaandotcom** [comment]
Thank you! My username is `adriaanvanrossum`

**Comment by olalonde** [comment]
Added you on npm + github :)
