### ISSUE TITLE
WebServer type

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [olalonde/pgtools#28]
When connecting to a webserver in the config options does pgtools need it to be tcp, udp, http, or something else?

**Comment by SpiderUnderUrBed** [comment]
I also want to know if the database is created locally so the data is being stored on whatever device is being used. Please reply to both questions

**Comment by adriaandotcom** [comment]
We basically use https://www.npmjs.com/package/pg and https://www.npmjs.com/package/pg-connection-string under the hood. This seems the relevant part for you: https://www.npmjs.com/package/pg-connection-string#connection-strings

 Let us know what you did find so it will be useful for others!

**Comment by SpiderUnderUrBed** [comment]
Yep it is TCP.

**Comment by SpiderUnderUrBed** [comment]
I forgot to ask if you can use tablespaces in pgtools [(click me)](https://www.postgresqltutorial.com/postgresql-create-tablespace/). I assumed this because you can specify a table space in createdb [(click me)](https://www.postgresql.org/docs/9.4/app-createdb.html). @adriaanvanrossum

**Comment by adriaandotcom** [comment]
Thanks for getting back to us. Tablespaces are currently not supported in pgtools. I wonder if that's a common use case though.

**Comment by SpiderUnderUrBed** [comment]
Tablespaces are important for extending your storage space and is useful for many cases so I strongly recommend you work on a tablespace option.

**Comment by adriaandotcom** [comment]
This is an open source project, you can't demand features. So I'm closing this issue.
