### ISSUE TITLE
Conditionally drop/create databases

### ISSUE THREAD

**Issue by navneetgarg123** [olalonde/pgtools#3]
Given that the current code errors out if you try to create an existing database, wouldn't it be better to just create it if it doesn't exist? Conversely for dropping, only if the table exists should you drop? 
If this is acceptable, I could probably send a pull request in fairly quickly.

**Comment by olalonde** [comment]
Sounds reasonable but it would be nice to follow the behaviour of the original Postgresql createdb/dropdb tools. Not sure how they behave in those cases (on mobile phone)

**Comment by samueljseay** [comment]
+1 for either some config options or new API methods to only create/drop if exists.

**Comment by olalonde** [comment]
Cool, I'll work a bit on this later. Can you guys star the repo? I didn't realise anyone was using this module :)

**Comment by maxharris9** [comment]
I've tried using this module, but it seems like it's kinda busted. (I'm looking for an easy way to set up a postgres db from node for integration testing.)

**Comment by alechirsch** [comment]
If you do this, it would be nice to have a function to check if a database exists or not

**Comment by RavenHursT** [comment]
I tried to implement this at a higher level.. should be a simple process of looking at the rejection error and swallowing it if it's just that the DB doesn't exist on drop... 

But I keep getting an odd error: https://github.com/olalonde/pgtools/issues/17

**Comment by adriaandotcom** [comment]
I want to start with a clean slate. So closing this issue as it's from 2015. Please reopen any issue if it's still a problem at the moment.
