### ISSUE TITLE
update yargs dep

### ISSUE THREAD

**Issue by yashcr07** [olalonde/pgtools#32]
`yargs 5.0.0` uses `yargs-parser 3.2.0` which has a vulnerability, is it possible to use a newer version of yargs?

**Comment by adriaandotcom** [comment]
Sure, would you mind adding a pull request?

**Comment by yashcr07** [comment]
Alright, let me try creating a PR

**Comment by yashcr07** [comment]
created #33

**Comment by ahmed-zubair12** [comment]
@adriaanvanrossum  any update on this?

**Comment by adriaandotcom** [comment]
~~I can't get a hold of the freelance developer that we hired to build this. Keep you posted.~~

This comment was posted in the wrong issue.

**Comment by freben** [comment]
That would be appreciated! Thanks.
