### ISSUE TITLE
pgtools.createdb is failing silently

### ISSUE THREAD

**Issue by RobStafford** [olalonde/pgtools#36]
Hello. Running current version of your tool. Running node 14.x. I have a script (https://github.com/RobStafford/To-Do-Calendar/blob/main/database/schemaPostgres.js) which has run successfully dozens of times. Now, when you run it, a console.log before or after the .createdb command fires, but nothing inside the command. Nothing is logged--no successes or failures. I have a teammate who was having the same problem the day before, then mine started acting the same way. That makes me suspect it might be related to a PR on our project, but I can't for the life of me see what the problem is. Help?

**Comment by adriaandotcom** [comment]
Do you have a minimal example of your code?

**Comment by olalonde** [comment]
@RobStafford can you test using the latest version of this library? There was a big refactor which might have solved this issue. It now only supports Promise API though.
