### ISSUE TITLE
New release to publish with the Yargs patch?

### ISSUE THREAD

**Issue by adamdmharvey** [olalonde/pgtools#51]
In March, the project seemed to get a good Yargs patch which fixes numerous transitive security vulnerabilities.

However, seems the version was not published - the latest to download from Npm is v1.0.0 which still contains Yargs v5.x.

Is it possible to cut a release including the most recent dep upgrade?

Thanks!

Ref: https://github.com/olalonde/pgtools/pull/50

**Comment by olalonde** [comment]
Sure, published to v1.0.1

**Comment by adamdmharvey** [comment]
Thanks!
